name: Changelog Automaker (Generate PR CL)

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      oref:
        description: 'Override REF'
        required: True

env:
  GIT_EMAIL: "action@github.com"
  GIT_NAME: "Changelog Automaker"
  GIT_BRANCH: "master"

jobs:
  MakeCL:
    runs-on: ubuntu-latest
    # discriminator to exclude forks
    if: github.repository == 'Tennessee116/Ofstation13'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 15
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install depends
        run: |
          python -m pip install --upgrade pip
          pip install ruamel.yaml PyGithub
      - name: Make CL
        env:
          GITHUB_TOKEN: ${{ secrets.BOSNIAN_TOKEN }}
          OVERRIDE_REF: ${{ github.event.inputs.oref }}
        run: python tools/changelog/generate_cl.py
